<?php

return [
    'notify_user' => true,
    'notify_user_on_ticket' => true,
    'mfa_required' => false,
    'ttl_minutes' => 60,
    'allowed_routes' => [
        'super-admin.support-view.stop',
        'portal.dashboard',
        'portal.orders.index',
        'portal.orders.show',
        'portal.shipments.index',
        'portal.shipments.show',
        'portal.settings.index',
        'portal.products.index',
        'portal.products.show',
        'portal.categories.index',
        'portal.categories.show',
        'portal.tickets.index',
        'portal.tickets.show',
        'portal.marketplaces.index',
        'portal.marketplaces.show',
        'portal.integrations.index',
        'portal.modules.index',
        'portal.modules.show',
        'portal.module-purchases.index',
        'portal.module-purchases.show',
        'portal.notification-hub.notifications.index',
        'portal.notification-hub.preferences.index',
        'portal.notification-hub.suppressions.index',
        'portal.notification-hub.suppressions.store',
        'portal.notification-hub.suppressions.destroy',
        'portal.integrations.health',
        'portal.incidents.index',
        'portal.incidents.show',
        'portal.incidents.assign',
        'portal.incidents.ack',
        'portal.incidents.resolve',
    ],
];
